import{useState}from"react";import{Cart,Footer,Products,Process,products}from"./Sections.jsx";
const occasions=["Все","День рождения","Работа","Отношения"];
export function App(){const[filter,setFilter]=useState("Все"),[cart,setCart]=useState({}),[open,setOpen]=useState(false),[note,setNote]=useState("");const shown=filter==="Все"?products:products.filter(x=>x.occasion===filter),count=Object.values(cart).reduce((a,b)=>a+b,0);function add(p){setCart(c=>({...c,[p.id]:(c[p.id]||0)+1}));setNote("«"+p.title+"» уже в корзине");setTimeout(()=>setNote(""),2200)}function choose(x){setFilter(x);document.querySelector("#catalog").scrollIntoView({behavior:"smooth"})}return <div>
<header className="header"><a className="wordmark" href="#top">БУМБУМАГА</a><nav><a href="#catalog">Каталог</a><a href="#process">Как это сделано</a><a href="#about">О нас</a></nav><button className="cart-link" onClick={()=>setOpen(true)}>Корзина <span>{count}</span></button></header>
<main id="top"><section className="hero"><div><p className="eyebrow">Поп-ап открытки с характером</p><h1>МЕМ, КОТОРЫЙ<br/>МОЖНО<br/>ПОДАРИТЬ</h1><p className="lead">Для друзей, коллег и тех, кому слов уже мало.</p><a className="primary" href="#catalog">Смотреть открытки</a></div><figure className="hero-popup" tabIndex="0"><img className="hero-backdrop" src="/assets/hero-gatsby-background.png" alt="Фон поп-ап открытки в стиле Великого Гэтсби"/><img className="hero-subject" src="/assets/hero-gatsby-subject.png" alt="Ди Каприо с бокалом поднимается из открытки"/><span className="hero-cover" aria-hidden="true"/><figcaption>Наведи — и бокал поднимется</figcaption></figure></section>
<section className="occasions"><p>Выберите повод — мы подберём уровень абсурда</p><div>{occasions.slice(1).map(x=><button key={x} onClick={()=>choose(x)}>{x}<small>Смотреть</small></button>)}</div></section>
<section className="catalog" id="catalog"><header><div><p className="eyebrow">Тираж ограничен здравым смыслом</p><h2>ПОПУЛЯРНОЕ</h2></div><div className="filters">{occasions.map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</div></header><Products items={shown} add={add}/></section>
<Process/></main>
<Footer/>{note&&<div className="toast">{note}</div>}<Cart open={open} close={()=>setOpen(false)} cart={cart} setCart={setCart}/></div>}
